name    'justinclayton-redis'
version '0.0.1'
source ''
author 'justinclayton'
license ''
summary 'Installs Redis server'
description 'Installs Redis server'
project_page ''

## Add dependencies, if any:
#dependency 'stahnma/epel', '>= 0.0.2'
